import { auth, db, storage } from "./firebase-config.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";
import { collection, doc, getDocs, setDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import { ref, uploadBytes, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-storage.js";

const TIPOS={
 cliente:[['identificacion','Identificación oficial'],['domicilio','Comprobante de domicilio'],['otros','Otros documentos']],
 repartidor:[['identificacion','Identificación oficial'],['domicilio','Comprobante de domicilio'],['licencia','Licencia de conducir'],['tarjeta_circulacion','Tarjeta de circulación'],['moto_frente','Fotografía de la moto — frente'],['moto_lateral','Fotografía de la moto — lateral'],['otros','Otros documentos']],
 negocio:[['representante','Identificación del representante'],['domicilio','Comprobante de domicilio'],['fiscal','Documento fiscal'],['permiso','Permiso o licencia del negocio'],['otros','Otros documentos']],
 admin:[['identificacion','Identificación oficial'],['domicilio','Comprobante de domicilio'],['otros','Otros documentos']]
};
const objetivo=new URLSearchParams(location.search);
const requestedUid=objetivo.get('uid');
const requestedStoreId=objetivo.get('storeId');
let usuario=null, soloLectura=false;
function cfg(){if(requestedStoreId)return {tipo:'negocio',id:requestedStoreId,tienda:true};if(objetivo?.tipo==='negocio'&&objetivo?.tiendaId)return {tipo:'negocio',id:objetivo.tiendaId,tienda:true};return {tipo:usuario.tipo,id:usuario.uid,tienda:false};}
function ext(file){const n=file.name.toLowerCase();return n.endsWith('.png')?'png':n.endsWith('.webp')?'webp':n.endsWith('.pdf')?'pdf':'jpg';}
function ruta(c,t,e){return c.tienda?`tiendas/${c.id}/documentos/${t}.${e}`:(c.tipo==='repartidor'?`repartidores/${c.id}/documentos/${t}.${e}`:`usuarios/${c.id}/documentos/${t}.${e}`);}
function col(c){return c.tienda?collection(db,'tiendas',c.id,'documentos'):collection(db,'usuarios',c.id,'documentos');}
function card(tipo,nombre,data,c){const d=document.createElement('article');d.className='documento-card';const ok=!!data;d.innerHTML=`<h3>${nombre}</h3><p>Archivo permitido: JPG, PNG, WEBP o PDF. Máximo 8 MB.</p><div class="documento-estado ${ok?'ok':'pendiente'}">${ok?'Documento cargado':'Pendiente de cargar'}</div><div class="documento-acciones">${ok?`<button class="ver">Ver documento</button>`:''}<label class="subir">${ok?'Reemplazar':'Subir documento'}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></label>${ok&&!soloLectura?'<button class="secundario eliminar">Eliminar</button>':''}</div>`;if(ok)d.querySelector('.ver').onclick=async()=>window.open(await getDownloadURL(ref(storage,data.storagePath)),'_blank');if(!soloLectura)d.querySelector('input').onchange=e=>subir(tipo,e.target.files[0],c);if(ok&&!soloLectura)d.querySelector('.eliminar').onclick=()=>eliminar(tipo,data,c);return d;}
async function subir(tipo,file,c){if(!file)return;if(file.size>8*1024*1024)return alert('El archivo supera el límite de 8 MB.');const tipos=['image/jpeg','image/png','image/webp','application/pdf'];if(!tipos.includes(file.type))return alert('Solo se permiten JPG, PNG, WEBP o PDF.');const ex=ext(file),path=ruta(c,tipo,ex),r=ref(storage,path);const oldRef=doc(col(c),tipo);try{const snap=await getDocs(col(c));for(const x of snap.docs){if(x.id===tipo&&x.data().storagePath&&x.data().storagePath!==path){try{await deleteObject(ref(storage,x.data().storagePath))}catch{}}}await uploadBytes(r,file,{contentType:file.type});await setDoc(oldRef,{tipoDocumento:tipo,nombre:file.name,storagePath:path,contentType:file.type,size:file.size,subidoPor:auth.currentUser.uid,subidoEn:serverTimestamp(),estado:'pendiente'},{merge:true});await cargar(c);alert('Documento guardado correctamente.')}catch(e){console.error(e);alert('No se pudo guardar el documento.')}}
async function eliminar(tipo,data,c){if(!confirm('¿Eliminar este documento?'))return;try{await deleteDoc(doc(col(c),tipo));if(data.storagePath)try{await deleteObject(ref(storage,data.storagePath))}catch{}await cargar(c)}catch(e){console.error(e);alert('No se pudo eliminar el documento.')}}
async function cargar(c){const lista=document.getElementById('listaDocumentos');const estado=document.getElementById('estadoDocumentos');lista.innerHTML='';const docs={};try{const snap=await getDocs(col(c));snap.forEach(x=>docs[x.id]=x.data());for(const [tipo,nombre] of (TIPOS[c.tipo]||TIPOS.cliente))lista.appendChild(card(tipo,nombre,docs[tipo],c));estado.textContent=soloLectura?'Expediente en modo consulta.':'Selecciona un archivo para cargar o reemplazarlo.'}catch(e){console.error(e);estado.textContent='No se pudieron cargar los documentos.'}}
onAuthStateChanged(auth,async u=>{if(!u)return location.href='login.html';const requested=!!(requestedUid||requestedStoreId);try{const userSnap=await (await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js')).getDoc(doc(db,'usuarios',u.uid));usuario=userSnap.exists()?{uid:u.uid,...userSnap.data()}:{uid:u.uid,tipo:'cliente'};if(requested){soloLectura=usuario.tipo==='admin';if(requestedUid){const t=await (await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js')).getDoc(doc(db,'usuarios',requestedUid));if(!t.exists())return;usuario={uid:requestedUid,...t.data()}}}const c=cfg();document.body.classList.toggle('solo-lectura',soloLectura);document.getElementById('tituloDocumentos').textContent=soloLectura?'Expediente / documentos':'Mis documentos';await cargar(c)}catch(e){console.error(e);document.getElementById('estadoDocumentos').textContent='No se pudo abrir el expediente.'}});
